# Etapa 1: Instalação de dependências
FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci

# Etapa 2: Build da aplicação
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# A variável NEXT_PUBLIC_API_URL será fornecida pelo Render em tempo de execução
RUN npm run build

# Etapa 3: Produção (Standalone)
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

# Copia os artefatos da build standalone
COPY --from=builder /app/public ./public
COPY --from=builder --chown=node:node /app/.next/standalone ./
COPY --from=builder --chown=node:node /app/.next/static ./.next/static

# Define usuário não-root (boa prática)
USER node

EXPOSE 3000

#ENV PORT=3000

# Inicia o servidor Node.js otimizado
CMD ["node", "server.js"]
