# render.yaml - Blueprint para Deploy no Render
# Documentação: https://render.com/docs/blueprint-spec

databases:
  # Banco de Dados PostgreSQL Gerenciado pelo Render
  - name: embrapa-db
    databaseName: vitivinicultura # Nome do banco de dados
    user: embrapa_user # Nome de usuário (Render pode adicionar sufixo )
    # plan: free # <-- REMOVIDA - Você selecionará o plano no dashboard do Render
    # A variável DATABASE_URL será injetada automaticamente nos serviços conectados

redis:
  # Cache Redis Gerenciado pelo Render
  - name: embrapa-cache
    plan: free # Plano free para Redis geralmente funciona bem no YAML
    # A variável REDIS_URL será injetada automaticamente nos serviços conectados

services:
  # Serviço 1: API Backend (Flask/Gunicorn)
  - type: web
    name: embrapa-api
    runtime: docker
    repo: https://github.com/gustavoimbelloni/projeto-embrapa # Render preenche automaticamente
    branch: master # Ou main, ajuste conforme sua branch principal
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: FLASK_APP
        value: src.main:app
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: embrapa-db
          property: connectionString
      - key: REDIS_URL
        fromRedis:
          name: embrapa-cache
          property: connectionString

  # Serviço 2: Frontend (Next.js )
  - type: web
    name: embrapa-frontend
    runtime: docker
    repo: https://github.com/gustavoimbelloni/projeto-embrapa # Render preenche automaticamente
    branch: master # Ou main, ajuste conforme sua branch principal
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: embrapa-api
          property: url