# render.yaml - Blueprint para Deploy no Render
# Documentação: https://render.com/docs/blueprint-spec

databases:
  # Banco de Dados PostgreSQL Gerenciado pelo Render
  - name: embrapa-db
    databaseName: vitivinicultura
    user: embrapa_user
    # Você selecionará o plano no dashboard do Render

services:
  # Serviço 1: API Backend (Flask/Gunicorn )
  # O serviço Redis será criado manualmente no dashboard
  - type: web
    name: embrapa-api
    runtime: docker
    repo: https://github.com/gustavoimbelloni/projeto-embrapa # Render preenche automaticamente
    branch: master # Ou main, ajuste conforme sua branch principal
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: FLASK_APP
        value: src.main:app
      - key: FLASK_ENV
        value: production
      # Conexão com o Banco de Dados Gerenciado
      - key: DATABASE_URL
        fromDatabase:
          name: embrapa-db
          property: connectionString
      # A variável REDIS_URL precisará ser adicionada manualmente no dashboard
      # após criar o serviço Redis manualmente, apontando para a connectionString dele.

  # Serviço 2: Frontend (Next.js )
  - type: web
    name: embrapa-frontend
    runtime: docker
    repo: https://github.com/gustavoimbelloni/projeto-embrapa # Render preenche automaticamente
    branch: master # Ou main, ajuste conforme sua branch principal
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    # A variável NEXT_PUBLIC_API_URL precisará ser adicionada manualmente
    # no dashboard após a API ter sua URL pública.
